services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web-starter-kit
    logging:
      driver: none
  redis:
    image: redis:7.4.0-alpine
    ports:
      - '6379:6379'
    logging:
      driver: none
  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
